# Generated by Django 3.2.19 on 2023-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenlist',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
