# Generated by Django 3.2.23 on 2024-02-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_tokenlist_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpSpeed_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('time', models.DecimalField(decimal_places=9, max_digits=12)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IpSpeed_g',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('time', models.DecimalField(decimal_places=9, max_digits=12)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='tokenlist',
            name='time',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
