# Generated by Django 3.2.23 on 2024-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20240201_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipspeed_a',
            name='time',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tokenlist',
            name='time',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
    ]
