# Generated by Django 3.2.23 on 2024-02-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20240201_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipspeed_a',
            name='time',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ipspeed_g',
            name='time',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tokenlist',
            name='time',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
    ]
