# Generated by Django 3.2.23 on 2024-02-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_board_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.TextField(max_length=2000000),
        ),
    ]
