# Generated by Django 3.2.23 on 2024-03-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
