# Generated by Django 5.0.4 on 2024-06-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_delete_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenlist',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
